"""initial_schema

Revision ID: a408ea57e03f
Revises: 
Create Date: 2026-07-26 12:25:55.818503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a408ea57e03f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('user_arn', sa.String(), nullable=False),
    sa.Column('access_key', sa.String(), nullable=False),
    sa.Column('encrypted_secret_key', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aws_accounts_id'), 'aws_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aws_accounts_id'), table_name='aws_accounts')
    op.drop_table('aws_accounts')
    # ### end Alembic commands ###
